apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend 
  labels:
    app: java-backend 
spec:
  selector:
    matchLabels:
      app: java-backend 
  template:
    metadata:
      labels:
        app: java-backend 
    spec:
      containers:
      - name: java-backend 
        image: java-backend-image-tilt_docker_build_with_restart_base 
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend 
spec:
  selector:
    matchLabels:
      app: angular-frontend 
  template:
    metadata:
      labels:
        app: angular-frontend 
    spec:
      containers:
      - name: angular-frontend 
        image: angular-frontend-image
        ports:
        - containerPort: 4200
