apiVersion: v1
kind: Service
metadata:
  name: java-svc
  labels:
    app: java-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-svc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
  labels:
    app: java-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: java-svc
    spec:
      containers:
        - name: java-backend
          env:
            - name: DATABASE_CONTAINER_NAME
              value: postgres-db-lb
          image: java-backend-image-tilt_docker_build_with_restart_base
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: angular-svc
  labels:
    app: angular-svc
spec:
  ports:
    - port: 4200
      protocol: TCP
      targetPort: 4200
  selector:
    app: angular-svc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: angular-svc
    spec:
      containers:
        - name: angular-frontend
          image: angular-frontend-image 
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: rails-svc
  labels:
    app: rails-svc
spec:
  ports:
    - port: 8081 
      protocol: TCP
      targetPort: 8081
  selector:
    app: rails-svc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  labels:
    app: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: rails-svc
    spec:
      containers:
        - name:  rails-app
          entrypoint: bash
          args:
            - bin/prod-run
          env:
            - name: MINIO_URL
              value: http://minio-db-lb:9000
            - name: SPRING_APP_URL
              value: http://java-svc:8080
            - name: PORT
              value: "8081"
            - name: DATABASE_URL
              value: postgresql://postgres-db-lb:5432
            - name: DATABASE_PASSWORD
              value: postgres
          image: rails-app-image 
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8081
