spring:
  datasource:
    url: "jdbc:postgresql://postgres-db-lb:5432/postgres"
    username: postgres
    password: postgres 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  liquibase:
    enabled: false
server:
  port:
    8080
  forward-headers-strategy: native
